<a href="https://colab.research.google.com/github/Shruti12377/Codelabz/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Numpy
#provides efficient storage, provides better ways of handling data for processing
#fast, easy to learn, uses relatively less memory to store data

import numpy as np


In [2]:
myarr=np.array([1,2,3])
myarr

array([1, 2, 3])

In [4]:
first=np.array([2,34,56,35],np.int8)
first

first.dtype

#int8= size of the input number by giging size 8 bytes we can not take the number which has size more than 8.

dtype('int8')

In [5]:
second=np.array([[1,2,3],[2,3,4],[3,4,5]])
second

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [9]:
second.dtype

dtype('int64')

dtype('int64')

In [11]:
second.shape

(3, 3)

In [8]:
second.size

9

In [13]:
zeros=np.zeros((2,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
rng=np.arange(15)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
lspace=np.linspace(1,100,12)
lspace

array([  1.,  10.,  19.,  28.,  37.,  46.,  55.,  64.,  73.,  82.,  91.,
       100.])

In [21]:
emp=np.empty((4,6))
emp

array([[    nan,     nan, 0.e+000,     nan, 5.e-324,     nan],
       [1.e-323,     nan, 5.e-324, 0.e+000, 1.e-323, 5.e-324],
       [5.e-324, 1.e-323, 0.e+000, 5.e-324,     nan, 1.e-323],
       [    nan, 5.e-324,     nan, 0.e+000,     nan,     nan]])

In [22]:
emp_like=np.empty_like(lspace)
emp_like

array([  1.,  10.,  19.,  28.,  37.,  46.,  55.,  64.,  73.,  82.,  91.,
       100.])

In [28]:
ide=np.identity(5)
ide

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [29]:
ide.shape

(5, 5)

In [26]:
third=np.arange(99)
third

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [27]:
third.reshape(3,33)

#however (3,31) is not possible

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [30]:
fourth=np.array([[1,2,3],[2,3,4],[4,5,6]])
fourth

array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6]])

In [31]:
fourth.sum(axis=0)

#axis 0= column (y axis)

array([ 7, 10, 13])

In [32]:
fourth.sum(axis=1)

#axis 1= row (x axis)

array([ 6,  9, 15])

In [33]:
#transpose the matrix

fourth.T

array([[1, 2, 4],
       [2, 3, 5],
       [3, 4, 6]])

In [34]:
fourth.flat

In [35]:
for item in fourth.flat:
  print(item)

1
2
3
2
3
4
4
5
6


In [36]:
#to show the number of dimensionals

fourth.ndim

2

In [38]:
fourth.nbytes

#shows bytes of array

72

In [41]:
#to print the maximum element from the index

fifth=np.array([1,3,45,56,89])
fifth.argmax()


4

In [42]:
fifth.argmin()

0

In [44]:
six=np.array([34,1,23,45,78,23])
six.argsort()

array([1, 2, 5, 0, 3, 4])

In [45]:
seven=np.array([[1,2,3],[5,6,7],[3,4,6]])
seven

array([[1, 2, 3],
       [5, 6, 7],
       [3, 4, 6]])

In [46]:
seven.argmin()

0

In [47]:
seven.argmax()

5

In [48]:
seven.argmax(axis=0)

array([1, 1, 1])

In [49]:
seven.argmax(axis=1)

array([2, 2, 2])

In [50]:
seven.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [52]:
seven.ravel()

array([1, 2, 3, 5, 6, 7, 3, 4, 6])

In [53]:
sum1=np.array([[1,5,2],[3,7,8],[1,2,6]])
sum2=np.array([[3,5,0],[2,3,5],[3,6,1]])

In [54]:
sum1+sum2

array([[ 4, 10,  2],
       [ 5, 10, 13],
       [ 4,  8,  7]])

In [55]:
sum1*sum2

array([[ 3, 25,  0],
       [ 6, 21, 40],
       [ 3, 12,  6]])

In [56]:
np.sqrt(sum1)

array([[1.        , 2.23606798, 1.41421356],
       [1.73205081, 2.64575131, 2.82842712],
       [1.        , 1.41421356, 2.44948974]])

In [57]:
np.sqrt(sum1*sum2)

array([[1.73205081, 5.        , 0.        ],
       [2.44948974, 4.58257569, 6.32455532],
       [1.73205081, 3.46410162, 2.44948974]])

In [61]:
sum1.sum()
sum1.max()
sum2.min()

0

In [62]:
np.where(sum1>3)

(array([0, 1, 1, 2]), array([1, 1, 2, 2]))

In [63]:
np.count_nonzero(sum1)

9